### ISSUE TITLE
Create flow diagram for project based on README https://github.com/erikrtn/bmed8813_icu#overview

### ISSUE THREAD

**Issue by erikrtn** [erikrtn/bmed8813_icu#58]

**Comment by mobatusi** [comment]
[ICU_SquentialMining_Flowchart.pdf](https://github.com/erikrtn/bmed8813_icu/files/974070/ICU_SquentialMining_Flowchart.pdf)

Preliminary flowchart, will modify to reflect changes in pipeline.

**Comment by erikrtn** [comment]
Why does Input Sequences have an arrow leading to Race, but not to the other User Inputs?

@aamkatz, any thoughts on this?

**Comment by mobatusi** [comment]
That was a mistake. fixed
[ICU_SquentialMining_Flowchart.pdf](https://github.com/erikrtn/bmed8813_icu/files/974841/ICU_SquentialMining_Flowchart.pdf)

**Comment by mobatusi** [comment]
[ICU_SquentialMining_Flowchart.pdf](https://github.com/erikrtn/bmed8813_icu/files/974953/ICU_SquentialMining_Flowchart.pdf)
Updated and added to paper in overleaf
