### ISSUE TITLE
Revise Phases in Methods; instead of 1A, IB, etc., instead describe a) preprocessing & cleaning, b) parsing, c) sequence mining, and d) confidence calculations and clustering.

### ISSUE THREAD

**Issue by erikrtn** [erikrtn/bmed8813_icu#62]

**Comment by mobatusi** [comment]
working on this in a separate overleaf document. I will upload afterwards when its ready

**Comment by mobatusi** [comment]
I've uploaded the methods to the final document, still need to add confidence. We don't have any clustering, so leaving that out for now.
